189 monitors  groups updating frontend so it works with backend
UA-Smart-Signage-Platform/Content-Manager-System-and-Content-Creator-Tool pull request #191
Opened 2024-09-10 11:23 UTC by pdPinho

### Issue

Closes #189 

### Reason for this change

Due to some changes in our database the backend required some adjustments whilst the frontend had to match those adjustments.

### Description of changes

- Updated `Monitors` and `Specific Monitor` pages to match BD and backend;
- Updated `GroupBar` to match backend;
- Updated and refactored some frontend code to use `react query`;
- Some miscellaneous fixes.

### Description of how you validated changes

Ran `docker compose up`
And on top of that tested multiple routes and functionalities to guarantee that things worked correctly.
 
### Checklist
- [X] I have tested my changes locally.
- [ ] I have updated the documentation to reflect my changes.
- [ ] I have added/updated unit tests (if applicable).
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://ua-smart-signage-platform.github.io/Documentation-Website/guidelines/)

### Aditional Information
Currently missing some verifications but nothing software-breaking experience type.

2024-09-11 12:21 UTC, pdPinho commented
Backend integration tests are currently failing, however it will be ignored for the time being.

2024-09-16 06:35 UTC, WildBunnie requested changes
apart from my question about the api permissions for file downloads all seems ok in the backend

2024-09-16 06:35 UTC, WildBunnie commented on backend/src/main/java/pt/ua/deti/uasmartsignage/configuration/SecurityConfig.java
is /api/files not what we use for the media player to download the files?

2024-09-17 08:12 UTC, pdPinho commented on backend/src/main/java/pt/ua/deti/uasmartsignage/configuration/SecurityConfig.java
You are correct. I will fix it immediately. :+1:

2024-09-17 08:18 UTC, merged