model entity shedule and create enpoints for that same entity
UA-Smart-Signage-Platform/Content-Manager-System-and-Content-Creator-Tool pull request #93
Opened 2024-04-17 22:02 UTC by DiogoSilva1904

### Issue

Closes #39 

### Reason for this change

Modeling the entity schedule, and making the respective serivces,repository and controllers.

### Description of changes

The entity schedule has been created along with its corresponding repository, services, and controllers. The controllers handle the following operations such as retrieving all schedules, fetching schedules by their unique IDs, deleting schedules, saving new schedules, and updating existing ones.Swagger documentation already done for the this controllers. 

### Description of how you validated changes

No unitary tests were made,

### Checklist
- [x] I have tested my changes locally.
- [x] I have updated the documentation to reflect my changes.
- [ ] I have added/updated unit tests (if applicable).
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://ua-smart-signage-platform.github.io/Documentation-Website/guidelines/)

### Aditional Information

2024-04-23 09:18 UTC, Rafa548 requested changes
Change PR description, still a minor issue in the sonarcloud

2024-04-24 10:02 UTC, Rafa548 approved these changes

2024-04-24 10:02 UTC, Rafa548 commented
lgtm

2024-04-24 14:43 UTC, merged

2024-04-28 18:01 UTC, fungame2270 reviewed
please make this changes

2024-04-28 18:01 UTC, fungame2270 commented on backend/uasmartsignage/src/main/java/deti/uas/uasmartsignage/Models/Schedule.java
> +    private String frequency;
change to int

2024-04-28 18:01 UTC, fungame2270 commented on backend/uasmartsignage/src/main/java/deti/uas/uasmartsignage/Models/Schedule.java
> +    private int nTimes;
this is not needed in bd

2024-04-28 18:01 UTC, fungame2270 commented on backend/uasmartsignage/src/main/java/deti/uas/uasmartsignage/Models/Schedule.java
> +
need to add start hour and end hour
and a list for weekday its a list of ints postgres accepts lists in bd

(the created on is good i dont know why its selected)

2024-04-28 18:01 UTC, fungame2270 commented on backend/uasmartsignage/src/main/java/deti/uas/uasmartsignage/Models/Schedule.java
> +    private LocalDate date;
this date is not needed

2024-04-28 18:31 UTC, DiogoSilva1904 commented
This changes will be adressed in a new issue. #102

2024-04-28 18:41 UTC, DiogoSilva1904 commented on backend/uasmartsignage/src/main/java/deti/uas/uasmartsignage/Models/Schedule.java
> +
@Column(name = "start_date")
    private LocalDateTime startDate;

    @Column(name = "end_date")
    private LocalDateTime endDate;    this two atribbutes have this format:"2007-12-03T10:15:30"  so with the addition of startHour and endHour can  both be erased(create a new attribute only with the date?)

2024-04-29 11:27 UTC, fungame2270 commented on backend/uasmartsignage/src/main/java/deti/uas/uasmartsignage/Models/Schedule.java
> +
needs to be passed only to date